label: Config Connector NetworkServicesTLSRoute
markdownDescription: Creates yaml for a NetworkServicesTLSRoute resource
insertText: |
  apiVersion: networkservices.cnrm.cloud.google.com/v1beta1
  kind: NetworkServicesTLSRoute
  metadata:
    name: \${1:networkservicestlsroute-name}
  spec:
    meshes:
    - name: \${2:networkservicestlsroute-dep}
    gateways:
    - name: \${3:networkservicestlsroute-dep}
    description: \${4:A test TcpRoute}
    location: \${5:global}
    rules:
    - matches:
      - sniHost:
        - \${6:*.foo.example.com}
        - \${7:foo.example.com}
        alpn:
        - \${8:h2}
        - \${9:http/1.1}
      action:
        destinations:
        - serviceRef:
            name: \${10:networkservicestlsroute-dep}
          weight: \${11:1}
    projectRef:
      external: \${12:projects/[PROJECT_ID?]}
