label: Config Connector NetworkServicesTCPRoute
markdownDescription: Creates yaml for a NetworkServicesTCPRoute resource
insertText: |
  apiVersion: networkservices.cnrm.cloud.google.com/v1beta1
  kind: NetworkServicesTCPRoute
  metadata:
    labels:
      \${1:foo}: \${2:bar}
    name: \${3:networkservicestcproute-name}
  spec:
    meshes:
    - name: \${4:networkservicestcproute-dep}
    gateways:
    - name: \${5:networkservicestcproute-dep}
    location: \${6:global}
    description: \${7:A test TcpRoute}
    rules:
    - matches:
      - address: \${8:10.0.0.1/32}
        port: \${9:7777}
      action:
        destinations:
        - serviceRef:
            name: \${10:networkservicestcproute-dep}
          weight: \${11:1}
    - matches:
      - address: \${12:10.0.0.1/0}
        port: \${13:1}
      action:
        originalDestination: \${14:false}
        destinations:
        - serviceRef:
            name: \${15:networkservicestcproute-dep}
          weight: \${16:1}
    projectRef:
      external: \${17:projects/[PROJECT_ID?]}
