label: Config Connector ServiceIdentity
markdownDescription: Creates yaml for a ServiceIdentity resource
insertText: |
  apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
  kind: ServiceIdentity
  metadata:
    name: \${1:serviceidentity-name}
  spec:
    projectRef:
      external: \${2:[PROJECT_ID?]}
    resourceID: \${3:pubsub.googleapis.com}
