apiVersion: v1
data:
  cnrm.controller: gcr.io/gke-release/cnrm/controller:411c879
  cnrm.deletiondefender: gcr.io/gke-release/cnrm/deletiondefender:411c879
  cnrm.recorder: gcr.io/gke-release/cnrm/recorder:411c879
  cnrm.unmanageddetector: gcr.io/gke-release/cnrm/unmanageddetector:411c879
  cnrm.webhook: gcr.io/gke-release/cnrm/webhook:411c879
  prom-to-sd: k8s.gcr.io/prometheus-to-sd:v0.9.1
kind: ConfigMap
metadata:
  annotations:
    components.gke.io/image-map: Images deployed by operator
  creationTimestamp: null
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    cnrm.cloud.google.com/operator-system: "true"
  name: config-images
  namespace: configconnector-operator-system
